#Pressure Points Maek Chi Ki
1-Yuehl Gyuhl|[strike wrist with soo doh]
2-Soo Sahm Ri|[Soo Doh strike @ elbow]
3-Chunn Boo|[Soo Doh strike to shoulder]
4-Geuk Chunn|[Gwahn Soo to armpit]
5-Hohn Soo|[Soo Doh to the right side of the neck]
6-Gaek Joo In|[Gahk Gwahn to right temple]
7-Hohn Soo|[Soo Doh to right side of the neck]
8-Dae Po|[Soo Doh to left ribs]
9-Ki Hae|[Gwahn Soo to belly button]
10-Goo Mi|[Joong Chi Gwuhn to sternum]
11-Yuhm Chohn|[Sah Ji Gwuhn to adams apple]
12-Jang Moon|[Pahl Kum Chi to right ribs]
13-Ah Moon|[Pahl Kum Chi to back of the neck]
14-Shin Juhng|[Pyung Soo to forehead]
15-Yoo Geun|[Pyung Soo to left ribs/heart]